name: learn-github-actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 #git clone  
    - name: Set Up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13" #python 설치: Jenkins의 플러그인 설치와 동일
    - name: Display Python version
      run: python --version #shell 명령어 수행: Jenkins의 sh "명령어"와 동일
